:github-tag: master
:github-repo: spring-cloud/spring-cloud-kubernetes
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
= Spring Cloud Kubernetes

include::intro.adoc[]

[[spring-cloud-kubernetes-install]]
== Install Kubernetes
TODO:
http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash

[[spring-cloud-kubernetes-discovery]]
== Service Discovery with Kubernetes

TODO:

=== Using the DiscoveryClient
Spring Cloud has support for https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#spring-cloud-feign[Feign] (a REST client builder) and also https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#spring-cloud-ribbon[Spring `RestTemplate`] using the logical service names instead of physical URLs.

You can also use the `org.springframework.cloud.client.discovery.DiscoveryClient` which provides a simple API for discovery clients that is not specific to Netflix, e.g.

----
@Autowired
private DiscoveryClient discoveryClient;

public String serviceUrl() {
    List<ServiceInstance> list = client.getInstances("STORES");
    if (list != null && list.size() > 0 ) {
        return list.get(0).getUri();
    }
    return null;
}
----

[[spring-cloud-kubernetes-hystrix]]
== Circuit Breaker with Hystrix

Applications can use the Hystrix Circuit Breaker provided by the Spring Cloud Netflix project by including this starter in the projects pom.xml: `spring-cloud-starter-hystrix`.  Hystrix doesn't depend on the Netflix Discovery Client. The `@EnableHystrix` annotation should be placed on a configuration class (usually the main class). Then methods can be annotated with `@HystrixCommand` to be protected by a circuit breaker. See http://projects.spring.io/spring-cloud/spring-cloud.html#_circuit_breaker_hystrix_clients[the documentation] for more details.


[[spring-cloud-kubernetes-turbine]]
== Hystrix metrics aggregation with Turbine and Kubernetes

Turbine (provided by the Spring Cloud Netflix project), aggregates multiple instances Hystrix metrics streams, so the dashboard can display an aggregate view. Turbine uses the `DiscoveryClient` interface to lookup relevant instances. To use Turbine with Spring Cloud Kubernetes, configure the Turbine application in a manner similar to the following examples:

.pom.xml
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-turbine</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-discovery</artifactId>
</dependency>
----

Notice that the Turbine dependency is not a starter. The turbine starter includes support for Netflix Eureka.

.application.yml
----
spring.application.name: turbine
applications: kuberneteshystrixclient
turbine:
  aggregator:
    clusterConfig: ${applications}
  appConfig: ${applications}
----

The `clusterConfig` and `appConfig` sections must match, so it's useful to put the comma-separated list of service ID's into a separate configuration property.

.Turbine.java
----
@EnableTurbine
@EnableDiscoveryClient
@SpringBootApplication
public class Turbine {
    public static void main(String[] args) {
        SpringApplication.run(DemoturbinecommonsApplication.class, args);
    }
}
----